normal_case = {
    "loan_amnt": 3800,
    "term": "36 months",
    "purpose": "debt_consolidation",
    "annual_inc": 56000,
    "emp_length": 10,
    "verification_status": "Not Verified",
    "home_ownership": "MORTGAGE",
    "open_acc": 8,
    "total_acc": 14,
    "mort_acc": 1,
    "delinq_2yrs": 0,
    "acc_now_delinq": 0,
    "pub_rec": 0,
    "pub_rec_bankruptcies": 0,
    "tax_liens": 0,
    "collections_12_mths_ex_med": 0,
    "inq_last_6mths": 1,
    "revol_bal": 3000,
    "tot_cur_bal": 145000,
    "total_bal_ex_mort": 8000,
    "avg_cur_bal": 1600,
    "open_acc_6m": 2,
    "acc_open_past_24mths": 4
}


mild_case = {
    "loan_amnt": 7000,
    "term": "36 months",
    "purpose": "debt_consolidation",
    "annual_inc": 52000,
    "emp_length": 8,
    "verification_status": "Not Verified",
    "home_ownership": "MORTGAGE",
    "open_acc": 6,
    "total_acc": 12,
    "mort_acc": 1,
    "delinq_2yrs": 1,
    "acc_now_delinq": 0,
    "pub_rec": 0,
    "pub_rec_bankruptcies": 0,
    "tax_liens": 0,
    "collections_12_mths_ex_med": 0,
    "inq_last_6mths": 2,
    "revol_bal": 9000,
    "tot_cur_bal": 130000,
    "total_bal_ex_mort": 14000,
    "avg_cur_bal": 1800,
    "open_acc_6m": 1,
    "acc_open_past_24mths": 5
}


fraud_case = {
    "loan_amnt": 250000,
    "term": "60 months",
    "purpose": "small_business",
    "annual_inc": 24000,
    "emp_length": 1,
    "verification_status": "Not Verified",
    "home_ownership": "RENT",
    "open_acc": 2,
    "total_acc": 4,
    "mort_acc": 0,
    "delinq_2yrs": 3,
    "acc_now_delinq": 1,
    "pub_rec": 1,
    "pub_rec_bankruptcies": 1,
    "tax_liens": 1,
    "collections_12_mths_ex_med": 2,
    "inq_last_6mths": 7,
    "revol_bal": 18000,
    "tot_cur_bal": 22000,
    "total_bal_ex_mort": 18000,
    "avg_cur_bal": 700,
    "open_acc_6m": 0,
    "acc_open_past_24mths": 1
}
